### ISSUE TITLE
output folder is empty

### ISSUE THREAD

**Issue by emans841** [r00t-3xp10it/trojanizer#3]
[☆] Trojanizer : start sfx archive compression ..
[☆] Config WINE path for icon replacement : done!
[☆] Copy all files to output folder : done!
[☆] Extract filenames from full paths : done!
[☆] Build SFX configuration file : done!
[☆] Use WINRAR to compress files : working ..
[☆] Trojanizer : All tasks completed ..
[☆] Report bugs: https://github.com/r00t-3xp10it/trojanizer/issues

even with this the ouput folder is empty

**Comment by r00t-3xp10it** [comment]
# iam lost ..

can you go inside **settings** file to check if all the settings are correct configurated ?
example: check if **paths** to softwares conrresponds to your system installed softwares ..
![Trojanizer v1.1-Stable](http://i.cubeupload.com/b1dziT.png)

---

Also take a look at this issue: https://github.com/r00t-3xp10it/trojanizer/issues/2

**Comment by emans841** [comment]
its working now,the problem is with win rar

**Comment by r00t-3xp10it** [comment]
Exelent news .. have fun ..
